# Generated by Django 5.2.7 on 2025-10-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFlowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MPANCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan_core', models.CharField(max_length=13, unique=True)),
                ('bcs_validation_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=50, unique=True)),
                ('meter_type', models.CharField(max_length=50)),
                ('mpan_core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='flow_processor.mpancore')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_register_id', models.CharField(max_length=50)),
                ('reading_date_time', models.DateTimeField()),
                ('register_reading', models.FloatField()),
                ('reset_date_time', models.DateTimeField(blank=True, null=True)),
                ('md_reset_count', models.IntegerField(blank=True, null=True)),
                ('reading_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('reading_method', models.CharField(max_length=50)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='flow_processor.meter')),
            ],
        ),
    ]
